<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>

<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>


<!-- CART CONTENT -->

    <!--CART HEADINGS -->
    <div class="hidden lg:flex w-full">
        <div class="w-full lg:w-3/6">
            <h4 class="mb-6 font-bold font-heading text-gray-500">Product details</h4>
        </div>
        <div class="w-full lg:w-1/6">
            <h4 class="mb-6 font-bold font-heading text-gray-500">Eenheidsprijs</h4>
        </div>
        <div class="w-full lg:w-1/6 text-center">
            <h4 class="mb-6 font-bold font-heading text-gray-500">Aantal</h4>
        </div>
        <div class="w-full lg:w-1/6 text-right">
            <h4 class="mb-6 font-bold font-heading text-gray-500">Product subtotaal</h4>
        </div>
    </div>
    <!--END CART HEADINGS -->

    <!-- PRODUCT LISTING -->
    <div class="mb-12 py-6 border-t border-b border-gray-200">

        <form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
              class="form form-cart">
            <?= $block->getBlockHtml('formkey') ?>
                <?php if ($block->getPagerHtml()): ?>
                    <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                         data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
                    </div>
                <?php endif ?>

<!--                <table id="shopping-cart-table"-->
<!--                       class="cart items data table"-->
<!--                       data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",-->
<!--               "updateCartActionContainer": "#update_cart_action_container"}}'>-->

                    <?php foreach ($block->getItems() as $_item): ?>
                        <?= $block->getItemHtml($_item) ?>
                    <?php endforeach ?>


<!--                </table>-->
                <?php if ($block->getPagerHtml()): ?>
                    <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                         data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
                    </div>
                <?php endif ?>

            <div class="cart main actions">
                <?php if ($block->getContinueShoppingUrl()): ?>
                    <a class="action continue"
                       href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
                       title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                        <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
                    </a>
                <?php endif; ?>
                <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
                    <button type="button"
                            name="update_cart_action"
                            data-cart-empty=""
                            value="empty_cart"
                            title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                            class="action clear" id="empty_cart_button">
                        <span><?= $block->escapeHtml(__('Clear Shopping Cart')) ?></span>
                    </button>
                <?php endif ?>
                <button type="submit"
                        name="update_cart_action"
                        data-cart-item-update=""
                        value="update_qty"
                        title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                        class="action update">
                    <span><?= $block->escapeHtml(__('Update Shopping Cart')) ?></span>
                </button>
                <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
            </div>
        </form>
    </div>
    <!-- END PRODUCT LISTING -->

<!-- END CART CONTENT -->


<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

