<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <div class="row">
        <div class="col md:w-1/2">
            <div class="page-title-wrapper">
                <div class="h1" class="page-title">
                    <span class="base" data-ui-id="page-title-wrapper"><?php echo __('Thank you for your purchase!'); ?></span>
                </div>
                <?php if ($block->getOrderId()): ?>
                    <?php if ($block->getCanViewOrder()) : ?>
                        <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
                    <?php else : ?>
                        <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <?php if ($block->getOrderId()): ?>
                <p><?php /* @escapeNotVerified */
                    echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
            <?php endif; ?>

            <?php echo $block->getAdditionalInfoHtml() ?>
        </div>

        <div class="actions-toolbar col md:w-1/2">
            <div class="primary">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('success_message')->toHtml();?>
                <a class="action primary continue" href="<?php /* @escapeNotVerified */
                echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */
                        echo __('Continue Shopping') ?></span></a>
            </div>
        </div>
    </div>
</div>
