<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/**
 * @var Link $block
 * @var Escaper $escaper
 */
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
            data-mage-init='{
                "Magento_Checkout/js/proceed-to-checkout":{
                    "checkoutUrl":"<?= $escaper->escapeJs($block->getCheckoutUrl()) ?>"
                }
            }'
            class="action primary checkout flex items-center align-middle block w-full py-4 px-4 bg-blue-600 hover:bg-blue-800 text-white font-bold font-heading uppercase rounded-md transition duration-200
            <?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()): ?>
                disabled="disabled"
            <?php endif; ?>>
        <svg class="flex-none h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
        </svg>
        <span class="flex-auto text-lg lg:text-2xl "><?= $escaper->escapeHtml(__('Proceed to Checkout')) ?></span>
    </button>
<?php endif?>
